# Check the documentation at https://goreleaser.com
project_name: argocd-cloudtruth-plugin
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
dockers:
  - image_templates:
    - "cloudtruth/{{.ProjectName}}:{{ .Tag }}"
    - "cloudtruth/{{.ProjectName}}:latest"
    extra_files:
    - plugin.yaml
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
