/*
CloudTruth Management API

CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.

API version: v1
Contact: support@cloudtruth.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudtruth

import (
	"encoding/json"
	"time"
)

// ParameterValuesValue struct for ParameterValuesValue
type ParameterValuesValue struct {
	// The value url.
	Url string `json:"url"`
	Id string `json:"id"`
	LedgerId string `json:"ledger_id"`
	// The environment this value is set in.
	Environment string `json:"environment"`
	// The environment id for this value.
	EnvironmentId string `json:"environment_id"`
	// The environment name for this value.  This is a convenience to avoid another query against the server to resolve the environment url into a name.
	EnvironmentName string `json:"environment_name"`
	// The parameter this value is for.
	Parameter string `json:"parameter"`
	// The parameter id for this value.
	ParameterId string `json:"parameter_id"`
	External *bool `json:"external,omitempty"`
	ExternalFqn *string `json:"external_fqn,omitempty"`
	ExternalFilter NullableString `json:"external_filter,omitempty"`
	// This field is deprecated and unused.
	ExternalError NullableString `json:"external_error"`
	ExternalStatus NullableValueExternalStatus `json:"external_status"`
	InternalValue NullableString `json:"internal_value,omitempty"`
	Interpolated *bool `json:"interpolated,omitempty"`
	// This is the actual content of the Value for the given parameter in the given environment.  If you request secret masking, no secret content will be included in the result and instead a series of asterisks will be used instead for the value.  Clients applying this value to a shell environment should set `<parameter_name>=<value>` even if `value` is the empty string.  If `value` is `null`, the client should unset that shell environment variable.
	Value NullableString `json:"value"`
	// If true, the `value` field has undergone template evaluation.
	Evaluated bool `json:"evaluated"`
	// Indicates the value content is a secret.  Normally this is `true` when the parameter is a secret. It is possible for a parameter to be a secret with a external value that is not a secret.  It is not possible to convert a parameter from a secret to a non-secret if any of the values are external and a secret.  Clients can check this condition by leveraging this field.  It is also possible for a parameter to not be a secret but for this value to be dynamic and reference a Parameter that is a secret.  In this case, we indicate the value is a secret.
	Secret NullableBool `json:"secret"`
	// The projects this value references, if dynamic.  This field is not valid for history requests.
	ReferencedProjects []string `json:"referenced_projects"`
	// The parameters this value references, if dynamic.  this field is not valid for history requests.
	ReferencedParameters []string `json:"referenced_parameters"`
	// The templates this value references, if dynamic.  This field is not valid for history requests.
	ReferencedTemplates []string `json:"referenced_templates"`
	CreatedAt time.Time `json:"created_at"`
	ModifiedAt NullableTime `json:"modified_at"`
}

// NewParameterValuesValue instantiates a new ParameterValuesValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParameterValuesValue(url string, id string, ledgerId string, environment string, environmentId string, environmentName string, parameter string, parameterId string, externalError NullableString, externalStatus NullableValueExternalStatus, value NullableString, evaluated bool, secret NullableBool, referencedProjects []string, referencedParameters []string, referencedTemplates []string, createdAt time.Time, modifiedAt NullableTime) *ParameterValuesValue {
	this := ParameterValuesValue{}
	this.Url = url
	this.Id = id
	this.LedgerId = ledgerId
	this.Environment = environment
	this.EnvironmentId = environmentId
	this.EnvironmentName = environmentName
	this.Parameter = parameter
	this.ParameterId = parameterId
	this.ExternalError = externalError
	this.ExternalStatus = externalStatus
	this.Value = value
	this.Evaluated = evaluated
	this.Secret = secret
	this.ReferencedProjects = referencedProjects
	this.ReferencedParameters = referencedParameters
	this.ReferencedTemplates = referencedTemplates
	this.CreatedAt = createdAt
	this.ModifiedAt = modifiedAt
	return &this
}

// NewParameterValuesValueWithDefaults instantiates a new ParameterValuesValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParameterValuesValueWithDefaults() *ParameterValuesValue {
	this := ParameterValuesValue{}
	return &this
}

// GetUrl returns the Url field value
func (o *ParameterValuesValue) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ParameterValuesValue) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ParameterValuesValue) SetUrl(v string) {
	o.Url = v
}

// GetId returns the Id field value
func (o *ParameterValuesValue) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ParameterValuesValue) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ParameterValuesValue) SetId(v string) {
	o.Id = v
}

// GetLedgerId returns the LedgerId field value
func (o *ParameterValuesValue) GetLedgerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LedgerId
}

// GetLedgerIdOk returns a tuple with the LedgerId field value
// and a boolean to check if the value has been set.
func (o *ParameterValuesValue) GetLedgerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LedgerId, true
}

// SetLedgerId sets field value
func (o *ParameterValuesValue) SetLedgerId(v string) {
	o.LedgerId = v
}

// GetEnvironment returns the Environment field value
func (o *ParameterValuesValue) GetEnvironment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *ParameterValuesValue) GetEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *ParameterValuesValue) SetEnvironment(v string) {
	o.Environment = v
}

// GetEnvironmentId returns the EnvironmentId field value
func (o *ParameterValuesValue) GetEnvironmentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvironmentId
}

// GetEnvironmentIdOk returns a tuple with the EnvironmentId field value
// and a boolean to check if the value has been set.
func (o *ParameterValuesValue) GetEnvironmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentId, true
}

// SetEnvironmentId sets field value
func (o *ParameterValuesValue) SetEnvironmentId(v string) {
	o.EnvironmentId = v
}

// GetEnvironmentName returns the EnvironmentName field value
func (o *ParameterValuesValue) GetEnvironmentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvironmentName
}

// GetEnvironmentNameOk returns a tuple with the EnvironmentName field value
// and a boolean to check if the value has been set.
func (o *ParameterValuesValue) GetEnvironmentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentName, true
}

// SetEnvironmentName sets field value
func (o *ParameterValuesValue) SetEnvironmentName(v string) {
	o.EnvironmentName = v
}

// GetParameter returns the Parameter field value
func (o *ParameterValuesValue) GetParameter() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Parameter
}

// GetParameterOk returns a tuple with the Parameter field value
// and a boolean to check if the value has been set.
func (o *ParameterValuesValue) GetParameterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Parameter, true
}

// SetParameter sets field value
func (o *ParameterValuesValue) SetParameter(v string) {
	o.Parameter = v
}

// GetParameterId returns the ParameterId field value
func (o *ParameterValuesValue) GetParameterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParameterId
}

// GetParameterIdOk returns a tuple with the ParameterId field value
// and a boolean to check if the value has been set.
func (o *ParameterValuesValue) GetParameterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParameterId, true
}

// SetParameterId sets field value
func (o *ParameterValuesValue) SetParameterId(v string) {
	o.ParameterId = v
}

// GetExternal returns the External field value if set, zero value otherwise.
func (o *ParameterValuesValue) GetExternal() bool {
	if o == nil || o.External == nil {
		var ret bool
		return ret
	}
	return *o.External
}

// GetExternalOk returns a tuple with the External field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParameterValuesValue) GetExternalOk() (*bool, bool) {
	if o == nil || o.External == nil {
		return nil, false
	}
	return o.External, true
}

// HasExternal returns a boolean if a field has been set.
func (o *ParameterValuesValue) HasExternal() bool {
	if o != nil && o.External != nil {
		return true
	}

	return false
}

// SetExternal gets a reference to the given bool and assigns it to the External field.
func (o *ParameterValuesValue) SetExternal(v bool) {
	o.External = &v
}

// GetExternalFqn returns the ExternalFqn field value if set, zero value otherwise.
func (o *ParameterValuesValue) GetExternalFqn() string {
	if o == nil || o.ExternalFqn == nil {
		var ret string
		return ret
	}
	return *o.ExternalFqn
}

// GetExternalFqnOk returns a tuple with the ExternalFqn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParameterValuesValue) GetExternalFqnOk() (*string, bool) {
	if o == nil || o.ExternalFqn == nil {
		return nil, false
	}
	return o.ExternalFqn, true
}

// HasExternalFqn returns a boolean if a field has been set.
func (o *ParameterValuesValue) HasExternalFqn() bool {
	if o != nil && o.ExternalFqn != nil {
		return true
	}

	return false
}

// SetExternalFqn gets a reference to the given string and assigns it to the ExternalFqn field.
func (o *ParameterValuesValue) SetExternalFqn(v string) {
	o.ExternalFqn = &v
}

// GetExternalFilter returns the ExternalFilter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ParameterValuesValue) GetExternalFilter() string {
	if o == nil || o.ExternalFilter.Get() == nil {
		var ret string
		return ret
	}
	return *o.ExternalFilter.Get()
}

// GetExternalFilterOk returns a tuple with the ExternalFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParameterValuesValue) GetExternalFilterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalFilter.Get(), o.ExternalFilter.IsSet()
}

// HasExternalFilter returns a boolean if a field has been set.
func (o *ParameterValuesValue) HasExternalFilter() bool {
	if o != nil && o.ExternalFilter.IsSet() {
		return true
	}

	return false
}

// SetExternalFilter gets a reference to the given NullableString and assigns it to the ExternalFilter field.
func (o *ParameterValuesValue) SetExternalFilter(v string) {
	o.ExternalFilter.Set(&v)
}
// SetExternalFilterNil sets the value for ExternalFilter to be an explicit nil
func (o *ParameterValuesValue) SetExternalFilterNil() {
	o.ExternalFilter.Set(nil)
}

// UnsetExternalFilter ensures that no value is present for ExternalFilter, not even an explicit nil
func (o *ParameterValuesValue) UnsetExternalFilter() {
	o.ExternalFilter.Unset()
}

// GetExternalError returns the ExternalError field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ParameterValuesValue) GetExternalError() string {
	if o == nil || o.ExternalError.Get() == nil {
		var ret string
		return ret
	}

	return *o.ExternalError.Get()
}

// GetExternalErrorOk returns a tuple with the ExternalError field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParameterValuesValue) GetExternalErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalError.Get(), o.ExternalError.IsSet()
}

// SetExternalError sets field value
func (o *ParameterValuesValue) SetExternalError(v string) {
	o.ExternalError.Set(&v)
}

// GetExternalStatus returns the ExternalStatus field value
// If the value is explicit nil, the zero value for ValueExternalStatus will be returned
func (o *ParameterValuesValue) GetExternalStatus() ValueExternalStatus {
	if o == nil || o.ExternalStatus.Get() == nil {
		var ret ValueExternalStatus
		return ret
	}

	return *o.ExternalStatus.Get()
}

// GetExternalStatusOk returns a tuple with the ExternalStatus field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParameterValuesValue) GetExternalStatusOk() (*ValueExternalStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalStatus.Get(), o.ExternalStatus.IsSet()
}

// SetExternalStatus sets field value
func (o *ParameterValuesValue) SetExternalStatus(v ValueExternalStatus) {
	o.ExternalStatus.Set(&v)
}

// GetInternalValue returns the InternalValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ParameterValuesValue) GetInternalValue() string {
	if o == nil || o.InternalValue.Get() == nil {
		var ret string
		return ret
	}
	return *o.InternalValue.Get()
}

// GetInternalValueOk returns a tuple with the InternalValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParameterValuesValue) GetInternalValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InternalValue.Get(), o.InternalValue.IsSet()
}

// HasInternalValue returns a boolean if a field has been set.
func (o *ParameterValuesValue) HasInternalValue() bool {
	if o != nil && o.InternalValue.IsSet() {
		return true
	}

	return false
}

// SetInternalValue gets a reference to the given NullableString and assigns it to the InternalValue field.
func (o *ParameterValuesValue) SetInternalValue(v string) {
	o.InternalValue.Set(&v)
}
// SetInternalValueNil sets the value for InternalValue to be an explicit nil
func (o *ParameterValuesValue) SetInternalValueNil() {
	o.InternalValue.Set(nil)
}

// UnsetInternalValue ensures that no value is present for InternalValue, not even an explicit nil
func (o *ParameterValuesValue) UnsetInternalValue() {
	o.InternalValue.Unset()
}

// GetInterpolated returns the Interpolated field value if set, zero value otherwise.
func (o *ParameterValuesValue) GetInterpolated() bool {
	if o == nil || o.Interpolated == nil {
		var ret bool
		return ret
	}
	return *o.Interpolated
}

// GetInterpolatedOk returns a tuple with the Interpolated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParameterValuesValue) GetInterpolatedOk() (*bool, bool) {
	if o == nil || o.Interpolated == nil {
		return nil, false
	}
	return o.Interpolated, true
}

// HasInterpolated returns a boolean if a field has been set.
func (o *ParameterValuesValue) HasInterpolated() bool {
	if o != nil && o.Interpolated != nil {
		return true
	}

	return false
}

// SetInterpolated gets a reference to the given bool and assigns it to the Interpolated field.
func (o *ParameterValuesValue) SetInterpolated(v bool) {
	o.Interpolated = &v
}

// GetValue returns the Value field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ParameterValuesValue) GetValue() string {
	if o == nil || o.Value.Get() == nil {
		var ret string
		return ret
	}

	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParameterValuesValue) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// SetValue sets field value
func (o *ParameterValuesValue) SetValue(v string) {
	o.Value.Set(&v)
}

// GetEvaluated returns the Evaluated field value
func (o *ParameterValuesValue) GetEvaluated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Evaluated
}

// GetEvaluatedOk returns a tuple with the Evaluated field value
// and a boolean to check if the value has been set.
func (o *ParameterValuesValue) GetEvaluatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Evaluated, true
}

// SetEvaluated sets field value
func (o *ParameterValuesValue) SetEvaluated(v bool) {
	o.Evaluated = v
}

// GetSecret returns the Secret field value
// If the value is explicit nil, the zero value for bool will be returned
func (o *ParameterValuesValue) GetSecret() bool {
	if o == nil || o.Secret.Get() == nil {
		var ret bool
		return ret
	}

	return *o.Secret.Get()
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParameterValuesValue) GetSecretOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Secret.Get(), o.Secret.IsSet()
}

// SetSecret sets field value
func (o *ParameterValuesValue) SetSecret(v bool) {
	o.Secret.Set(&v)
}

// GetReferencedProjects returns the ReferencedProjects field value
func (o *ParameterValuesValue) GetReferencedProjects() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ReferencedProjects
}

// GetReferencedProjectsOk returns a tuple with the ReferencedProjects field value
// and a boolean to check if the value has been set.
func (o *ParameterValuesValue) GetReferencedProjectsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferencedProjects, true
}

// SetReferencedProjects sets field value
func (o *ParameterValuesValue) SetReferencedProjects(v []string) {
	o.ReferencedProjects = v
}

// GetReferencedParameters returns the ReferencedParameters field value
func (o *ParameterValuesValue) GetReferencedParameters() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ReferencedParameters
}

// GetReferencedParametersOk returns a tuple with the ReferencedParameters field value
// and a boolean to check if the value has been set.
func (o *ParameterValuesValue) GetReferencedParametersOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferencedParameters, true
}

// SetReferencedParameters sets field value
func (o *ParameterValuesValue) SetReferencedParameters(v []string) {
	o.ReferencedParameters = v
}

// GetReferencedTemplates returns the ReferencedTemplates field value
func (o *ParameterValuesValue) GetReferencedTemplates() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ReferencedTemplates
}

// GetReferencedTemplatesOk returns a tuple with the ReferencedTemplates field value
// and a boolean to check if the value has been set.
func (o *ParameterValuesValue) GetReferencedTemplatesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferencedTemplates, true
}

// SetReferencedTemplates sets field value
func (o *ParameterValuesValue) SetReferencedTemplates(v []string) {
	o.ReferencedTemplates = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ParameterValuesValue) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ParameterValuesValue) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ParameterValuesValue) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetModifiedAt returns the ModifiedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *ParameterValuesValue) GetModifiedAt() time.Time {
	if o == nil || o.ModifiedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ModifiedAt.Get()
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParameterValuesValue) GetModifiedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModifiedAt.Get(), o.ModifiedAt.IsSet()
}

// SetModifiedAt sets field value
func (o *ParameterValuesValue) SetModifiedAt(v time.Time) {
	o.ModifiedAt.Set(&v)
}

func (o ParameterValuesValue) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["url"] = o.Url
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["ledger_id"] = o.LedgerId
	}
	if true {
		toSerialize["environment"] = o.Environment
	}
	if true {
		toSerialize["environment_id"] = o.EnvironmentId
	}
	if true {
		toSerialize["environment_name"] = o.EnvironmentName
	}
	if true {
		toSerialize["parameter"] = o.Parameter
	}
	if true {
		toSerialize["parameter_id"] = o.ParameterId
	}
	if o.External != nil {
		toSerialize["external"] = o.External
	}
	if o.ExternalFqn != nil {
		toSerialize["external_fqn"] = o.ExternalFqn
	}
	if o.ExternalFilter.IsSet() {
		toSerialize["external_filter"] = o.ExternalFilter.Get()
	}
	if true {
		toSerialize["external_error"] = o.ExternalError.Get()
	}
	if true {
		toSerialize["external_status"] = o.ExternalStatus.Get()
	}
	if o.InternalValue.IsSet() {
		toSerialize["internal_value"] = o.InternalValue.Get()
	}
	if o.Interpolated != nil {
		toSerialize["interpolated"] = o.Interpolated
	}
	if true {
		toSerialize["value"] = o.Value.Get()
	}
	if true {
		toSerialize["evaluated"] = o.Evaluated
	}
	if true {
		toSerialize["secret"] = o.Secret.Get()
	}
	if true {
		toSerialize["referenced_projects"] = o.ReferencedProjects
	}
	if true {
		toSerialize["referenced_parameters"] = o.ReferencedParameters
	}
	if true {
		toSerialize["referenced_templates"] = o.ReferencedTemplates
	}
	if true {
		toSerialize["created_at"] = o.CreatedAt
	}
	if true {
		toSerialize["modified_at"] = o.ModifiedAt.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableParameterValuesValue struct {
	value *ParameterValuesValue
	isSet bool
}

func (v NullableParameterValuesValue) Get() *ParameterValuesValue {
	return v.value
}

func (v *NullableParameterValuesValue) Set(val *ParameterValuesValue) {
	v.value = val
	v.isSet = true
}

func (v NullableParameterValuesValue) IsSet() bool {
	return v.isSet
}

func (v *NullableParameterValuesValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParameterValuesValue(val *ParameterValuesValue) *NullableParameterValuesValue {
	return &NullableParameterValuesValue{value: val, isSet: true}
}

func (v NullableParameterValuesValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParameterValuesValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


