name: Release Go project

on:
  push:
    tags:
      - "v*"

env:
  CI: true

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
        id: go

      - name: Set environment from cloudtruth
        uses: cloudtruth/configure-action@v2
        with:
          apikey: "${{ secrets.CLOUDTRUTH_API_KEY }}"
          project: "deploy"
          environment: "production"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Make client stubs
        run: make client

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
